{{- range .Values.topics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    strimzi.io/cluster: bike-parts-finder
spec:
  partitions: {{ .partitions }}
  replicas: {{ .replicas }}
  config:
    {{- range $key, $value := .config }}
    {{ $key }}: {{ $value }}
    {{- end }}
{{- end }}
