apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  # Storage
  - storage/gp3-storage-class.yaml

  # Kafka resources
  - kafka/kafka-cluster.yaml
  - kafka/topics.yaml

  # Application components
  - app/backend-api.yaml
  - app/scraper.yaml
  - app/consumer.yaml
  - app/frontend.yaml

# Create necessary namespaces
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: app-configs
    namespace: app
    literals:
      - ENVIRONMENT=dev
      - API_VERSION=v1

secretGenerator:
  - name: postgres-credentials
    namespace: database
    type: Opaque
    literals:
      - username=bpf
      - password=change-me-in-production

  - name: redis-credentials
    namespace: database
    type: Opaque
    literals:
      - password=change-me-in-production

patchesStrategicMerge: []  # Empty array, add environment specific patches as needed
