replicas:
  kafka: 3
  zookeeper: 3

storage:
  class: gp3
  size: 100Gi

resources:
  kafka:
    requests:
      memory: 2Gi
      cpu: 500m
    limits:
      memory: 4Gi
      cpu: 1000m
  zookeeper:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

topics:
  - name: scrape-requests
    partitions: 3
    replicas: 3
    config:
      retention.ms: 604800000  # 7 days
      segment.bytes: 1073741824  # 1GB
  - name: scrape-results
    partitions: 3
    replicas: 3
    config:
      retention.ms: 604800000  # 7 days
      segment.bytes: 1073741824  # 1GB
