environment:
  name: develop

api:
  image:
    repository: localhost:5000/bike-parts-finder-api
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

scraper:
  image:
    repository: localhost:5000/bike-parts-finder-scraper
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

consumer:
  image:
    repository: localhost:5000/bike-parts-finder-consumer
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

frontend:
  image:
    repository: localhost:5000/bike-parts-finder-frontend
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

database:
  host: postgres-postgresql.default.svc.cluster.local
  port: 5432
  name: bikepartsfinder
  useSecret: true
  secretName: postgres-credentials
  secretUserKey: username
  secretPasswordKey: password

redis:
  host: redis-master.default.svc.cluster.local
  port: 6379
  useSecret: true
  secretName: redis-credentials
  secretPasswordKey: password

kafka:
  brokers: kafka-headless.default.svc.cluster.local:9092
  requestTopic: scrape-requests
  resultTopic: scrape-results
