environment: develop
region: us-east-2

# Common configurations
replicaCounts:
  api: 1
  frontend: 1
  scraper: 1
  consumer: 1
  postgres: 1
  redis: 1
  kafka: 1
  zookeeper: 1

# Storage configuration
storage:
  class: gp3
  postgres:
    size: 20Gi
  redis:
    size: 8Gi
  kafka:
    size: 50Gi
  prometheus:
    size: 20Gi
  grafana:
    size: 5Gi

# Resource configurations
resources:
  api:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  frontend:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  scraper:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  consumer:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Backup configuration
backup:
  schedule: "0 1 * * *"  # Daily at 1 AM
  retention: "168h"      # 7 days

# Ingress configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  host: develop.bikepartsfinder.example.com

# Scraper configuration
scraper:
  concurrency: 5
  rateLimit: 1
