environment: production
region: us-east-2

# Common configurations
replicaCounts:
  api: 3
  frontend: 3
  scraper: 3
  consumer: 3
  postgres: 3
  redis: 3
  kafka: 3
  zookeeper: 3

# Storage configuration
storage:
  class: gp3
  postgres:
    size: 100Gi
  redis:
    size: 20Gi
  kafka:
    size: 100Gi
  prometheus:
    size: 100Gi
  grafana:
    size: 10Gi

# Resource configurations
resources:
  api:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  frontend:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  scraper:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  consumer:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

# Backup configuration
backup:
  schedule: "0 */6 * * *"  # Every 6 hours
  retention: "720h"        # 30 days

# Ingress configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-2:ACCOUNT_ID:certificate/CERTIFICATE_ID"
  host: bikepartsfinder.example.com

# Scraper configuration
scraper:
  concurrency: 10
  rateLimit: 2
