FROM node:24.4.1-alpine

WORKDIR /app

# Copy only package files first to leverage Docker cache
COPY package.json .npmrc ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY . .

# Start development server
EXPOSE 3000
ENV NODE_OPTIONS=--no-deprecation
ENV DISABLE_ESLINT_PLUGIN=true
CMD ["npm", "start"]
