replicaCount: 1

image:
  repository: ${REGISTRY}/bike-parts-finder-api
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

environment:
  name: develop

database:
  host: postgres-postgresql.database.svc.cluster.local
  port: 5432
  name: bikepartsfinder
  useSecret: true
  secretName: postgres-credentials
  secretUserKey: username
  secretPasswordKey: password

redis:
  host: redis-master.database.svc.cluster.local
  port: 6379
  useSecret: true
  secretName: redis-credentials
  secretPasswordKey: password

kafka:
  brokers: bike-parts-finder-kafka-bootstrap.kafka.svc.cluster.local:9092
  requestTopic: scrape-requests
  resultTopic: scrape-results

aws:
  region: us-east-2

probes:
  liveness:
    path: /health
    port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    path: /ready
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
