apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  configManagementPlugins: |
    - name: helmfile
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm plugin install https://github.com/databus23/helm-diff || true && helm repo update"]
      generate:
        command: ["/bin/sh", "-c"]
        args: ["cd $ARGOCD_APP_SOURCE_PATH && helmfile -e default -l name=$HELMFILE_RELEASE template"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, logs, *, *, allow
    p, role:admin, exec, *, */*, allow
    g, admin, role:admin
